---
development:
  cloud_name: dku8toha8
  api_key: '787123817524689'
  api_secret: ZcepAdHte4TiNMYrYl4oGN0jlRw
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: dku8toha8
  api_key: '787123817524689'
  api_secret: ZcepAdHte4TiNMYrYl4oGN0jlRw
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: dku8toha8
  api_key: '787123817524689'
  api_secret: ZcepAdHte4TiNMYrYl4oGN0jlRw
  enhance_image_tag: true
  static_image_support: false
